# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20170601_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
    ]
