# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 14:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_endereco_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to=settings.AUTH_USER_MODEL, verbose_name='Endereço do usuário'),
        ),
    ]
