# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20170606_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.CharField(default=999, max_length=30, verbose_name='Celular'),
            preserve_default=False,
        ),
    ]
