# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 16:58
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Item')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True, verbose_name='Slug')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to=settings.AUTH_USER_MODEL, verbose_name='Criador do Item')),
            ],
            options={
                'verbose_name_plural': 'Itens',
                'verbose_name': 'Item',
            },
        ),
        migrations.CreateModel(
            name='ItemPacote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_item', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='item', unique=True, verbose_name='Slug')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pacote', to='pacotes.Item', verbose_name='Item')),
            ],
            options={
                'verbose_name_plural': 'Quantidade-Itens',
                'verbose_name': 'Quantidade-Item',
            },
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Pacote')),
                ('quantidade_pessoas', models.PositiveIntegerField(verbose_name='Quantidade de Pessoas')),
                ('restricoes', models.CharField(choices=[('vegetariano', 'Vegetariano'), ('regional', 'Regional')], max_length=50, verbose_name='Tipo do Pacote')),
                ('preco', models.FloatField(verbose_name='Preço do Pacote')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique_with=('preco',), verbose_name='Slug')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes', to=settings.AUTH_USER_MODEL, verbose_name='Dono do Pacote')),
            ],
            options={
                'verbose_name_plural': 'Pacotes',
                'verbose_name': 'Pacote',
            },
        ),
        migrations.AddField(
            model_name='itempacote',
            name='pacote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pacotes.Pacote', verbose_name='Pacote do Item'),
        ),
    ]
