# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 17:51
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Item')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='ItemPacote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_item', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='item', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Quantidade-Item',
                'verbose_name_plural': 'Quantidade-Itens',
            },
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Pacote')),
                ('quantidade_pessoas', models.PositiveIntegerField(verbose_name='Quantidade de Pessoas')),
                ('restricoes', models.CharField(choices=[('vegetariano', 'Vegetariano'), ('regional', 'Regional')], max_length=50, verbose_name='Tipo do Pacote')),
                ('preco', models.FloatField(verbose_name='Preço do Pacote')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique_with=('preco',), verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Pacote',
                'verbose_name_plural': 'Pacotes',
            },
        ),
    ]
