# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 01:30
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0005_auto_20170606_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='nome', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='itempacote',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='item', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='nome', unique_with=('preco',), verbose_name='Slug'),
        ),
    ]
