# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0008_pacote_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descrição do Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='preco',
            field=models.FloatField(default=10, verbose_name='Preço do Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacote',
            name='codigo_pag_seguro',
            field=models.CharField(default=123, max_length=32, unique=True, verbose_name='Código do Pacote'),
            preserve_default=False,
        ),
    ]
