# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0010_auto_20170628_1536'),
        ('pacotes', '0009_auto_20170629_0100'),
    ]

    operations = [
    ]
