# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0011_merge_20170629_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacote',
            name='restricoes',
        ),
    ]
