# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0012_remove_pacote_restricoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacote',
            name='codigo_pag_seguro',
        ),
    ]
