# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 17:26
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Evento')),
                ('quantidade_pessoas', models.PositiveIntegerField(verbose_name='Quantidade de Pessoas')),
                ('data', models.DateTimeField(verbose_name='Data do Evento')),
                ('local', models.CharField(max_length=200, verbose_name='Local do Evento')),
                ('restricoes', models.CharField(choices=[('vegetariano', 'Vegetariano'), ('regional', 'Regional')], max_length=50, verbose_name='Tipos de Alimentos')),
                ('orcamento', models.FloatField(verbose_name='Orçamento para o Evento')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique_with=('data',), verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
