# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:48
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Evento')),
                ('quantidade_pessoas', models.PositiveIntegerField(verbose_name='Quantidade de Pessoas')),
                ('data', models.DateTimeField(verbose_name='Data do Evento')),
                ('local', models.CharField(max_length=200, verbose_name='Local do Evento')),
                ('restricoes', models.CharField(choices=[('vegetariano', 'Vegetariano'), ('regional', 'Regional')], max_length=50, verbose_name='Tipos de Alimentos')),
                ('orcamento', models.FloatField(verbose_name='Orçamento para o Evento')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique_with=('data',), verbose_name='Slug')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
            ],
        ),
    ]
