# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_auto_20170605_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocompleto',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='evento.Evento', verbose_name='Evento'),
        ),
    ]
