# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0009_auto_20170605_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocompleto',
            name='contratante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor', to=settings.AUTH_USER_MODEL, verbose_name='Contratante'),
        ),
        migrations.AlterField(
            model_name='eventocompleto',
            name='pacote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacote', to='pacotes.Pacote', verbose_name='Pacote do Evento'),
        ),
    ]
