# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0002_auto_20170601_1751'),
        ('evento', '0011_auto_20170605_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='pacotes',
            field=models.ManyToManyField(related_name='pacotes', to='pacotes.Pacote', verbose_name='Pacotes do Evento'),
        ),
    ]
