# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0012_evento_pacotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocompleto',
            name='contratante',
        ),
        migrations.RemoveField(
            model_name='eventocompleto',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='eventocompleto',
            name='pacote',
        ),
        migrations.DeleteModel(
            name='EventoCompleto',
        ),
    ]
