# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0014_auto_20170606_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='evento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='evento.Evento', verbose_name='Local do evento'),
        ),
    ]
