# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0016_auto_20170610_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='entregue',
            field=models.BooleanField(default=False, verbose_name='Pacote entregue ao evento'),
        ),
    ]
