# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0017_evento_entregue'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.CharField(default=999, max_length=400, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
