# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0019_auto_20170620_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estatus',
            field=models.CharField(default='Aguardando pagamento', max_length=40, verbose_name='Estatus da compra'),
        ),
    ]
