# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0022_remove_evento_restricoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='estatus',
        ),
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(default='Aguardando pagamento', max_length=40, verbose_name='Status da compra'),
        ),
    ]
